
{{ config(materialized='view') }}

WITH ORDERS AS
(
SELECT O_ORDERKEY,C_CUSTKEY,O_CUSTKEY,O_ORDERDATE,O_ORDERSTATUS,O_TOTALPRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS
LEFT JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER
ON O_CUSTKEY = C_CUSTKEY
WHERE YEAR(O_ORDERDATE) = '1996' AND O_ORDERSTATUS = 'O'
),

CO AS 
(
SELECT C_CUSTKEY, MONTH(O_ORDERDATE) MON ,SUM(O_TOTALPRICE) TOTAL
FROM ORDERS
GROUP BY C_CUSTKEY, MONTH(O_ORDERDATE)
ORDER BY MONTH(O_ORDERDATE)
)
SELECT * FROM CO
